### ISSUE TITLE
Support AIC or BIC-based selection of best lambda

### ISSUE THREAD

**Issue by tomwenseleers** [pbreheny/ncvreg#11]
Was wondering if it would be hard to incorporate AIC or BIC-based selection (or adjusted R2 for gaussian models) of the best lambda, as that's a lot faster than cross-validation based lambda selection? For gaussian glmnet's I saw this is incorporated in function ic.glmnet in package HDeconometrics, https://insightr.wordpress.com/2017/04/06/lasso-adalasso-and-the-glmnet-package/
Do you think something similar could be done for ncvreg models?

**Comment by pbreheny** [comment]
This is already supported:

```
data(prostate)
X <- as.matrix(prostate[,1:8])
y <- prostate$lpsa
fit <- ncvreg(X,y)
AIC(fit)
BIC(fit)
```

In fact, `ncvreg` works with `logLik()`, so any object-oriented function that requires a `logLik` method will work with `ncvreg` as well.
