### ISSUE TITLE
Error occured when applying ncvreg() with mapply()

### ISSUE THREAD

**Issue by simplegendz** [pbreheny/ncvreg#17]
Hi, I run into a weird problem when trying to evaluate the performance of SCAD on multiple models by applying ncvreg with mapply.
For simplicity, I tried following codes.
x1 and x2 are two design matrices and y1 and y2 are corresponding response vectors.
Define `lx = list(x1, x2)` and `ly = list(y1, y2)`.
Both `r1 = ncvreg(x1, y1, penalty = "SCAD")` and `r2 = ncvreg(x2, y2, penalty = "SCAD")` work perfectly.
Moreover, the code `R = mapply(function(x, y) cv.ncvreg(x, y, penalty = "SCAD"), lx, ly)` also works fine.
However, the code `R = mapply(function(x, y) ncvreg(x, y, penalty = "SCAD"), lx, ly)` fails with the error information "Error in sys.call(-1)[[1]] == "local_mfdr" : comparison (1) is possible only for atomic and list types " on Mac, Linux and Windows.
I am not sure how to fix this problem, especially cv.ncvreg works perfectly in this case. 
Thanks.

**Comment by pbreheny** [comment]
OK, this should be fixed now (for the GitHub version, not fixed on CRAN yet).  Thanks for bringing it to my attention!

If this is not fixed, please re-open the issue and let me know.
