### ISSUE TITLE
Removing Intercept and standardization

### ISSUE THREAD

**Issue by LucaIns** [pbreheny/ncvreg#18]
Hi! Thank you very much for this package.

I was wondering if there is an easy workaround to (possibly) exclude the intercept term?
Furthermore, is it necessary to standardize all the features? 
For instance, I would try to avoid it for dummy variables.

Thank you in advance.

**Comment by pbreheny** [comment]
It is intentionally not an option to remove standardization because it it almost always wrong to do so.  Definitely wrong not to standardize dummy variables.  However, as of ncvreg 3.12, there is a function, `ncvfit()` that allows a direct API to the fitting algorithm with no preprocessing of any kind (no intercept, no standardization, etc.).

**Comment by jolars** [comment]
Why do you think it's definitely wrong not to standardize dummy variables, @pbreheny? We actually just wrote a paper about this (<https://arxiv.org/abs/2501.03821>), and it does not seem like there is an obvious (one-size-fits-all) choice for how to standardize dummy variables (or indeed any other binary variable).

**Comment by pbreheny** [comment]
I suppose "definitely wrong" is an exaggeration; the penalty is a prior and any prior *could* make sense in certain scenarios. My statement is primarily based on the analogy between variable selection and testing. Not standardizing dummy variables would be akin to testing the different dummy variables at different alpha values (different type 1 error cutoffs).

**Comment by pbreheny** [comment]
But I'll read your paper -- maybe it'll change my mind!

**Comment by jolars** [comment]
I see, thanks! I realize it may have sounded as if I were advocating for not doing any kind of normalization at all, but I agree that that's rarely optimal. I'm just not sure that standardization (as one among many types of normalization strategies) is necessarily correct in every situation.
