### ISSUE TITLE
Possible memory leak in cdfit_cox_dh

### ISSUE THREAD

**Issue by ECuris** [pbreheny/ncvreg#20]
While performing simulations, I noticed a memory leak that lead to fill all memory when millions of call to cdfit_cox_dh are done.
By quickly looking at the code, it may come from the two pointers r and h that are assigned using Calloc on lines 71 and 72, but do not seem to be freed/frozen (they do not appear in the call to cleanupCox, and I could not find any other call to Free()).

**Comment by ECuris** [comment]
I'm glad it was useful.
For what it's worth, I managed to detect it using a (long) loop and simultaneously launching top in another terminal on linux... But that makes it long to identify the exact problem source when starting from a complex code.
Did you considered the use of valgrind to make such checks? I'm not familiar with its use with R, but some links on google suggest it may be helpful for all bugs concerning memory management... and is definitly a great tool when programming in C!

**Comment by pbreheny** [comment]
Well, I should have been more specific.  On the one hand, yes, if I call `survfit()` while running R with the valgrind debugger option, and then manually go over the output, then I do see two `1,096 bytes in 1 blocks are definitely lost` warnings -- one at line 71 and the other at line 72 -- and they go away with the new commit.

What I meant was that I'm not aware of a good way to automate these kinds of checks.  For example, if you run `R CMD check --use-valgrind ncvreg_3.11.2.tar.gz`, there is no indication of any problem, so Travis CI, etc., won't alert me.  Theoretically, I could tell myself to check for memory leaks every time I change the C code, but knowing myself, if a test isn't automated, I probably won't go out of my way to run it.

**Comment by ECuris** [comment]
Sorry for the misunderstanding… That indeed becomes tricky!
