### ISSUE TITLE
Error in .Call("standardize", X) :    "standardize" not resolved from current namespace (ncvreg)

### ISSUE THREAD

**Issue by SupertallAndy** [pbreheny/ncvreg#21]
Here is what I get when I run the sampling code of the function std().

> X <- matrix(rnorm(50), 10, 5)
> S <- std(X)
Error in .Call("standardize", X) : 
  "standardize" not resolved from current namespace (ncvreg)

Anything wrong? Thank you so much!

**Comment by pbreheny** [comment]
There appears to be something wrong with your setup; perhaps reinstall ncvreg?

```r
install.packages('ncvreg')
```
