### ISSUE TITLE
Can I introduce weights on samples when doing ncvfit?

### ISSUE THREAD

**Issue by markov10000** [pbreheny/ncvreg#32]
For example, In rawfit_gaussian.c let

v[j] = wsqsum(X, w, n, j)/n;
z[j] = wcrossprod(X, r, w, n, j)/n + v[j]*a[j];

Is there an easier way to do this?

**Comment by pbreheny** [comment]
I'm not entirely clear on what you're trying to do, but if you've got sample weights, you can just multiply them through and create a new X and y:

```
yy = sqrt(w) * y
XX = X * sqrt(w)
ncvfit(XX, yy)
```

If you write out the least squares loss function, you can see that it's the same for weighted X,y as for unweighted XX, yy. Does that help? If not, I need to know more about what you have in mind.

**Comment by markov10000** [comment]
I think it solves my problem. I am doing time-varying regression using kernel weights.
