### ISSUE TITLE
user supplied lambda sequence throws error 

### ISSUE THREAD

**Issue by tabpeter** [pbreheny/ncvreg#44]
For testing purposes, I am using ncvreg with a user-supplied lambda sequence. However, this throws an error: 

`data(Prostate);
fit <- ncvreg(Prostate$X, Prostate$y, lambda = c(0.1, 0.2))`

Error in if (digits < 0L) digits <- 6L else { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In lam_names(lambda) : NaNs produced

**Comment by pbreheny** [comment]
`lambda` should be supplied in a decreasing sequence:

```r
data(Prostate)
fit <- ncvreg(Prostate$X, Prostate$y, lambda = c(0.2, 0.1))
```

However, the user should certainly get a better error message (or the lambdas should just be reordered, perhaps with a warning).
